declare const assetTable: {
    doesAssetTagExist: string;
    addAssetToAssetRegister: string;
    addAssetFileAttachment: string;
    updateAssetFixedStatus: string;
    updateAssetLifeSpan: string;
    updateAssetAcquisitionDate: string;
    updateAssetLocation: string;
    updateAssetStatus: string;
    updateAssetCustodian: string;
    updateAssetAcquisitionCost: string;
    updateAssetInsuranceValue: string;
    updateAssetCategory: string;
    getAssetTags: string;
    disposeAsset: string;
    getAssetCategoryName: string;
    updateAssetResidualValue: string;
    getCloseBookValue: string;
    getAccumulatedDepreciation: string;
    getAssetDetails: string;
    insertAssetTag: string;
    unallocate: string;
    insertDepreciationSchedule: string;
    assetCategories: string;
    getAllAssets: string;
    deleteAsset: string;
    getAssetNetAndTotal: string;
    getAssetAddedInLast12Months: string;
    doesBarCodeExist: string;
    searchBySerialNo: string;
    updateAsset: string;
    searchForAsset: string;
    getAssetID: string;
};
export default assetTable;
