export default assetTable;
declare namespace assetTable {
    export { doesAssetIDExist as doesAssetTagExist };
    export { addAssetToAssetRegister };
    export { addAssetFileAttachment };
    export { updateAssetFixedStatus };
    export { updateAssetLifeSpan };
    export { updateAssetAcquisitionDate };
    export { updateAssetLocation };
    export { updateAssetStatus };
    export { updateAssetCustodian };
    export { updateAssetAcquisitionCost };
    export { updateAssetInsuranceValue };
    export { updateAssetCategory };
    export { getAssetTags };
    export { disposeAsset };
    export { getAssetCategoryName };
    export { updateAssetResidualValue };
    export { getCloseBookValue };
    export { getAccumulatedDepreciation };
    export { getAssetDetails };
    export { insertAssetTag };
    export { unallocate };
    export { insertDepreciationSchedule };
    export { assetCategories };
    export { getAllAssets };
    export { deleteAsset };
    export { getAssetNetAndTotal };
    export { getAssetAddedInLast12Months };
    export { doesBarCodeExist };
    export { searchBySerialNo };
    export { updateAsset };
    export { searchForAsset };
    export { getAssetID };
}
declare const doesAssetIDExist: "SELECT barcode FROM Asset WHERE assetID = $1";
declare const addAssetToAssetRegister: "INSERT INTO Asset (barcode, noInBuilding, code, description, serialNumber, acquisitionDate, locationID, residualValue,\n    condition, responsibleUsername, acquisitionCost, categoryID, usefulLife, depreciationType, depreciationPercent) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)";
declare const addAssetFileAttachment: "INSERT INTO Asset_File (assetTag, attachment) VALUES ($1, $2)";
declare const updateAssetFixedStatus: "UPDATE Asset SET isFixed = $1 WHERE assetTag = $2";
declare const updateAssetLifeSpan: "UPDATE Asset SET assetLifeSpan = $1 WHERE assetTag = $2";
declare const updateAssetAcquisitionDate: "UPDATE Asset SET acquisitionDate = $1 WHERE assetTag = $2";
declare const updateAssetLocation: "UPDATE Asset SET locationID = $1 WHERE assetTag = $2";
declare const updateAssetStatus: "UPDATE Asset SET status = $1 WHERE assetTag = $2";
declare const updateAssetCustodian: "UPDATE Asset SET custodianName = $1 WHERE assetTag = $2";
declare const updateAssetAcquisitionCost: "UPDATE Asset SET acquisitionCost = $1 WHERE assetTag = $2";
declare const updateAssetInsuranceValue: "UPDATE Asset SET insuranceValue = $1 WHERE assetTag = $2";
declare const updateAssetCategory: "UPDATE Asset SET categoryID = $1 WHERE assetTag = $2";
declare const getAssetTags: "SELECT assetTag FROM Asset";
declare const disposeAsset: "DELETE FROM Asset WHERE assettag = $1";
declare const getAssetCategoryName: "SELECT name FROM Category WHERE ID = (SELECT categoryID from Asset WHERE assetTag = $1)";
declare const updateAssetResidualValue: "UPDATE Asset SET residualValue = $1 WHERE assetTag = $2";
declare const getCloseBookValue: "SELECT closingBookValue FROM DepreciationSchedule WHERE assetid = $1 AND year = $2";
declare const getAccumulatedDepreciation: "SELECT SUM(depreciationExpense) FROM DepreciationSchedule WHERE assetid = $1;";
declare const getAssetDetails: "\n    SELECT a.barcode, a.noInBuilding, a.code, a.description, a.serialnumber, a.acquisitiondate, a.condition, \n    a.responsibleUsername, a.acquisitioncost, a.residualvalue, a.usefulLife, a.depreciationtype, a.depreciationpercent,\n    l.name as locationname, c.name as categoryname FROM Asset as a JOIN Location as l ON a.locationid = l.id \n    JOIN Category as c ON a.categoryid = c.id WHERE a.assetID = $1;\n";
declare const insertAssetTag: "INSERT INTO Tags(commandCode, hardwareKey, tagRecNums, antNo, pc, epcID, crc) VALUES ($1, $2, $3, $4, $5, $6, $7)";
declare const unallocate: "UPDATE Asset SET custodianname = null WHERE assettag = $1";
declare const insertDepreciationSchedule: "INSERT INTO DepreciationSchedule (year, assetID, openingbookvalue, depreciationexpense, accumulateddepreciation, closingbookvalue) VALUES ($1, $2, $3, $4, $5, $6)";
declare const assetCategories: "SELECT c.name, COUNT(*) FROM Asset a JOIN Category c ON c.id = a.categoryid GROUP BY c.id";
declare const getAllAssets: "SELECT a.assetid, a.barcode, a.description, a.condition, c.name AS category, a.serialNumber, l.name AS location FROM Asset a FULL JOIN Location l ON l.id = a.locationid FULL JOIN Category c ON a.categoryid = c.id WHERE a.assetid IS NOT NULL AND a.deleted = false";
declare const deleteAsset: "DELETE FROM Assets WHERE barcode = $1";
declare const getAssetNetAndTotal: "SELECT SUM(acquisitionCost) AS netValue, COUNT(*) AS total FROM Asset";
declare const getAssetAddedInLast12Months: "SELECT COUNT(*) AS last12mths FROM Asset WHERE acquisitionDate > (NOW() - INTERVAL '1 YEAR')";
declare const doesBarCodeExist: "SELECT * FROM Asset WHERE barcode = $1";
declare const searchBySerialNo: "SELECT a.barcode, a.description, a.condition, c.name AS category, a.serialNumber, l.name AS location FROM Asset a FULL JOIN Location l ON l.id = a.locationid FULL JOIN Category c ON a.categoryid = c.id WHERE a.serialNumber = $1";
declare const updateAsset: "UPDATE Asset SET $1 = $2 WHERE assetid = $3";
declare const searchForAsset: "SELECT a.assetid, a.barcode, a.description, a.condition, c.name AS category, a.serialNumber, l.name AS location FROM Asset a FULL JOIN Location l ON l.id = a.locationid FULL JOIN Category c ON a.categoryid = c.id WHERE a.textsearchable_index_col @@ websearch_to_tsquery($1)";
declare const getAssetID: "SELECT assetid FROM Asset WHERE barcode = $1";
