declare function isAnyEmpty(arr: any): boolean;
declare function checkIfBoolean(x: any, errorMessage: any): void;
declare function checkIfNumberisPositive(x: any, errorMessage: any): void;
declare function checkIfNumberisGreaterThanZero(x: any, errorMessage: any): void;
declare function checkIfString(x: any, errorMessage: any): void;
declare function checkIfValidDate(x: any, errorMessage: any): Date;
declare function verifyDatabaseFetchResults(fetchResult: any, errorMessage: any): void;
declare function isFetchResultEmpty(fetchResult: any): boolean;
declare function checkIfInList(list: any, item: any, errorMessage: any): void;
declare function addErrorHandlingToAsyncFunction(func: any, errorMessage: any, ...params: any[]): Promise<any>;
declare function assertThatAsynchronousFunctionFails(func: any, errorMessage: any, ...params: any[]): Promise<void>;
declare function assertThatAsyncFunctionReturnsRightThing(func: any, itemToReturn: any, ...params: any[]): Promise<void>;
declare function assertThatAsyncFunctionReturnsNull(func: any, ...params: any[]): Promise<void>;
declare function assertThatFunctionWorks(func: any, ...params: any[]): Promise<void>;
declare function returnFetchedResultsFromDatabase(query: any, arguements: any, valueWanted: any): Promise<any>;
declare const utility: {
    isAnyEmpty: typeof isAnyEmpty;
    checkIfBoolean: typeof checkIfBoolean;
    checkIfNumberisPositive: typeof checkIfNumberisPositive;
    checkIfValidDate: typeof checkIfValidDate;
    verifyDatabaseFetchResults: typeof verifyDatabaseFetchResults;
    checkIfInList: typeof checkIfInList;
    addErrorHandlingToAsyncFunction: typeof addErrorHandlingToAsyncFunction;
    checkIfNumberisGreaterThanZero: typeof checkIfNumberisGreaterThanZero;
    assertThatAsynchronousFunctionFails: typeof assertThatAsynchronousFunctionFails;
    assertThatAsyncFunctionReturnsRightThing: typeof assertThatAsyncFunctionReturnsRightThing;
    assertThatAsyncFunctionReturnsNull: typeof assertThatAsyncFunctionReturnsNull;
    isFetchResultEmpty: typeof isFetchResultEmpty;
    assertThatFunctionWorks: typeof assertThatFunctionWorks;
    returnFetchedResultsFromDatabase: typeof returnFetchedResultsFromDatabase;
    checkIfString: typeof checkIfString;
};
export default utility;
